<?php 
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
	$image = 'new_products_content_widget_grid';
	$item = $block->getSlide();
?>

<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('AHT_Slider/css/owl.carousel.min.css')?>">
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('AHT_Slider/css/owl.theme.default.min.css')?>">
<?php if ($block->getModuleStatus()): ?>
	<?php if ($block->getSlideStatus()): ?>
		<div class="owl-carousel owl-theme">
				<?php foreach ($item as $items): ?>
		        <div class="item product product-item">
		            <div class="product-item-info" data-container="product-grid">
		                <a href="<?php echo $block->getProductUrl($items); ?>" class="product photo product-item-photo" tabindex="-1">
                    		<?php echo $block->getImage($items, $image)->toHtml(); ?>
		                </a>
		                <div class="product details product-item-details">
		                    <strong class="product name product-item-name">
			                    <a class="product-item-link" 
			                    href="<?php echo $block->getProductUrl($items); ?>">
                                    <?php echo $block->escapeHtml($items->getName()); ?>
			                	</a>
		                    </strong>
		                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="1" data-price-box="product-id-1">
	                        <?php echo $block->getReviewsSummaryHtml($items, $templateType); ?>
	                        <?php echo $block->getProductPrice($items); ?>
	                        <?php echo $block->getProductDetailsHtml($items); ?>
		                    </div>
		                    <div class="product-item-inner">
		                        <div class="product actions product-item-actions">
		                            <div class="actions-primary">
                                    <?php if ($items->isSaleable()): ?>
                                        <?php if ($items->getTypeInstance()->hasRequiredOptions($items)): ?>
                                            <button class="action tocart primary mageplaza-product-slider-button"
                                                    data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($items) ?>"}}'
                                                    type="button" title="<?php echo __('Add to Cart') ?>">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($items), ['product' => $items->getEntityId()])
                                            ?>
                                            <button class="action tocart primary mageplaza-product-slider-button"
                                                    data-post='<?php echo $postData; ?>'
                                                    type="button" title="<?php echo __('Add to Cart') ?>">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php endif; ?>
	                                    <?php else: ?>
	                                        <?php if ($items->getIsSalable()): ?>
	                                            <div class="stock available"><span><?php echo __('In stock') ?></span>
	                                            </div>
	                                        <?php else: ?>
	                                            <div class="stock unavailable">
	                                                <span><?php echo __('Out of stock') ?></span>
	                                            </div>
	                                        <?php endif; ?>
	                                    <?php endif; ?>
	                                </div>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
		        <?php endforeach; ?>
		</div>
	<?php else: ?>
		<div class="products wrapper grid products-grid">
		    <ol class="products list items product-items">
				<?php foreach ($item as $items): ?>
		        <li class="item product product-item">
		            <div class="product-item-info" data-container="product-grid">
		                <a href="<?php echo $block->getProductUrl($items); ?>" class="product photo product-item-photo" tabindex="-1">
                    		<?php echo $block->getImage($items, $image)->toHtml(); ?>
		                </a>
		                <div class="product details product-item-details">
		                    <strong class="product name product-item-name">
			                    <a class="product-item-link" 
			                    href="<?php echo $block->getProductUrl($items); ?>">
                                    <?php echo $block->escapeHtml($items->getName()); ?>
			                	</a>
		                    </strong>
		                    <div class="price-box price-final_price" data-role="priceBox" data-product-id="1" data-price-box="product-id-1">
	                        <?php echo $block->getReviewsSummaryHtml($items, $templateType); ?>
	                        <?php echo $block->getProductPrice($items); ?>
	                        <?php echo $block->getProductDetailsHtml($items); ?>
		                    </div>
		                    <div class="product-item-inner">
		                        <div class="product actions product-item-actions">
		                            <div class="actions-primary">
                                    <?php if ($items->isSaleable()): ?>
                                        <?php if ($items->getTypeInstance()->hasRequiredOptions($items)): ?>
                                            <button class="action tocart primary mageplaza-product-slider-button"
                                                    data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($items) ?>"}}'
                                                    type="button" title="<?php echo __('Add to Cart') ?>">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($items), ['product' => $items->getEntityId()])
                                            ?>
                                            <button class="action tocart primary mageplaza-product-slider-button"
                                                    data-post='<?php echo $postData; ?>'
                                                    type="button" title="<?php echo __('Add to Cart') ?>">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php endif; ?>
	                                    <?php else: ?>
	                                        <?php if ($items->getIsSalable()): ?>
	                                            <div class="stock available"><span><?php echo __('In stock') ?></span>
	                                            </div>
	                                        <?php else: ?>
	                                            <div class="stock unavailable">
	                                                <span><?php echo __('Out of stock') ?></span>
	                                            </div>
	                                        <?php endif; ?>
	                                    <?php endif; ?>
	                                </div>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </li>
		        <?php endforeach; ?>
		    </ol>
		</div>
	<?php endif; ?>
<?php endif; ?>
		<script>
		    (function  () {
		        require(["jquery","owlCarousel"],function($) {
		            $(document).ready(function() {
		                $(".owl-carousel").owlCarousel({
		                    navigation : true, 
							loop:true,
							margin:30,
							nav:true,
							autoplay:true,
							autoplayTimeout:1000,
							items : 5
							
		                });
		            });
		        });
		    })();
		</script>
