<?php
        $productCollection = $block->getProductCollection();
      ?>  
      
        
            <table style="width:700px; border:1px solid black; text-align:center;">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>SKU</th>
                </tr>

                <?php 
                        foreach($productCollection as $display){
                ?>
        <form action="<?php echo $block->getUrl('slider/product/add'); ?>" method="post" id="form-validate">

                <tr>
                    <td><?php echo $display->getEntityID() ?></td>
                    <td><?php echo $display->getName() ?></td>
                    <td><?php echo $display->getSKU() ?></td>
                    <td><input  type="hidden" value="<?php echo $display->getEntityID() ?>" name="id" />
                        <input type="submit" value="disable">
                    </td>
                </tr>
        </form>
                <?php  } ?>

        </table>
